package aim4.im.v2i.policy.utils;

import aim4.im.v2i.reservation.AczManager;
import aim4.im.v2i.reservation.ReservationGridManager;
import aim4.msg.v2i.Request;

/**
 * The reservation parameter record generated by processProposals()
 */
public class ReserveParam {
    /**
     * The VIN of a vehicle
     */
    private int vin;
    /**
     * The successful proposal
     */
    private Request.Proposal successfulProposal;
    /**
     * The reservation plan
     */
    private ReservationGridManager.Plan gridPlan;
    /**
     * The ACZ manager
     */
    private AczManager aczManager;
    /**
     * The ACZ plan
     */
    private AczManager.Plan aczPlan;

    /**
     * Create a reservation parameter record.
     *
     * @param vin                the VIN of vehicle
     * @param successfulProposal the successful proposal
     * @param gridPlan           the reservation plan
     * @param aczManager         the ACZ manager
     * @param aczPlan            the ACZ plan
     */
    public ReserveParam(int vin, Request.Proposal successfulProposal, ReservationGridManager.Plan gridPlan,
                        AczManager aczManager, AczManager.Plan aczPlan) {
        this.vin = vin;
        this.successfulProposal = successfulProposal;
        this.gridPlan = gridPlan;
        this.aczManager = aczManager;
        this.aczPlan = aczPlan;
    }

    /**
     * Get the VIN of the vehicle
     */
    public int getVin() {
        return vin;
    }

    /**
     * Get the successful proposal
     */
    public Request.Proposal getSuccessfulProposal() {
        return successfulProposal;
    }

    /**
     * Get the reservation plan
     */
    public ReservationGridManager.Plan getGridPlan() {
        return gridPlan;
    }

    /**
     * Get the ACZ manager
     */
    public AczManager getAczManager() {
        return aczManager;
    }

    /**
     * Get the ACZ reservation plan
     */
    public AczManager.Plan getAczPlan() {
        return aczPlan;
    }
}

